kind: pipeline
name: default

steps:
- name: test
  image: maven:3-jdk-8
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
- name: publish
   image: plugins/docker
   repo: dokloud/swam-docker
   username: ${DOCKER_USERNAME}
   password: ${DOCKER_PASSWORD}
   when:
     branch: main
