kind: pipeline
name: default

steps:
- name: test
  image: maven:3-jdk-8
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
- name: docker  
  image: plugins/docker
  settings:
    repo: dokloud/swam-docker
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    tags:
      - latest
- name: terraform
  image: jmccann/drone-terraform:5
  pull: always
  settings:
    tf_version: 1.0.0
    root_dir: infrastructure/
    actions:
      - validate
      - plan
